### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by exersalza**

### CODE REVIEW

**Comment by exersalza** [comment]
New deobfuscation method :POOGERS:

image

**Comment by exersalza** [comment]
image

**Comment by ZerXGIT** [comment]
Maybe print the attack url from the Performhttp request

**Comment by exersalza** [comment]
it does @ZerXGIT or isn't it?
or do you mean that it should show inside the logfile as an extra key-value thingi?

**Comment by ZerXGIT** [comment]
Yea extra thingi for the special pepole. Like this Url: http://xyz.me/penls

**Comment by exersalza** [comment]
Got it, I'll add it tomorrow @ZerXGIT 
image

**Comment by exersalza** [comment]
@ZerXGIT It's implemented.

**Comment by exersalza** [comment]
@ZerXGIT here's your screenshot
image

**Comment by ZerXGIT** [comment]
LGTM

**Review by ZerXGIT — APPROVED** [review]
LGTM

**Pull request merged**
